server:
  port: 8080 # 启动端口

logging:
  config: classpath:logback.xml
  level:
    root: info
#配置微服务地址
url:
  #订单微服务
  orderUrl: http://localhost:8002
  #用户微服务
  userUrl: http://localhost:8003
  #购物车微服务
  shoppingUrl: http://localhost:8004
# ===== 自定义swagger配置 ===== #
swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: springfox swagger 3.0整合Demo
  try-host: http://localhost:${server.port}